//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptEntry.ImportService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReceiptEntry.ImportService.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SaveFile xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Merchants&gt;
        ///    &lt;Merchant&gt;
        ///      &lt;ID&gt;6f07df1e-2300-48ab-9752-2d27cd02cbb7&lt;/ID&gt;
        ///      &lt;Name&gt;3btech&lt;/Name&gt;
        ///      &lt;Values i:nil=&quot;true&quot;/&gt;
        ///    &lt;/Merchant&gt;
        ///    &lt;Merchant&gt;
        ///      &lt;ID&gt;9883a97c-5427-4fea-9495-64631295c351&lt;/ID&gt;
        ///      &lt;Name&gt;A Mountain Church of God&lt;/Name&gt;
        ///      &lt;Values i:nil=&quot;true&quot;/&gt;
        ///    &lt;/Merchant&gt;
        ///    &lt;Merchant&gt;
        ///      &lt;ID&gt;98f2ff81-9d3d-4a44-b271-dddfa0074852&lt;/ID&gt;
        ///      &lt;Name&gt;Advance Auto Parts&lt;/Name&gt;
        ///      &lt;Values i:nil=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string receipts {
            get {
                return ResourceManager.GetString("receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ShoppingList xmlns=&quot;http://www.mapa.com/apps/shoppingList/data&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;Items&gt;&lt;ShoppingListItem&gt;&lt;ID&gt;dd05ff74-9d95-4ba1-99ac-7bb90c60b48c&lt;/ID&gt;&lt;Name&gt;Gas&lt;/Name&gt;&lt;/ShoppingListItem&gt;&lt;ShoppingListItem&gt;&lt;ID&gt;81188830-fc9b-43d2-8fc1-e8a8a20ad102&lt;/ID&gt;&lt;Name&gt;Happy Meal&lt;/Name&gt;&lt;/ShoppingListItem&gt;&lt;ShoppingListItem&gt;&lt;ID&gt;1c28c0ce-8585-46b9-939c-caa56ec72d85&lt;/ID&gt;&lt;Name&gt;Trash Bags&lt;/Name&gt;&lt;/ShoppingListItem&gt;&lt;ShoppingListItem&gt;&lt;ID&gt;135c723b-829a-4090-bfc4-0d119c05da4a&lt;/ID&gt;&lt;Name&gt;Paper Towel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shoppingItems {
            get {
                return ResourceManager.GetString("shoppingItems", resourceCulture);
            }
        }
    }
}
